
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  simulate:
    build: .
    command: python app/scripts/simulate_market.py
    depends_on:
      - redis
    ports:
      - "8765:8765"
  ingest:
    build: .
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
    command: python -m  app.ingest.websocket_client
    depends_on:
      - simulate
      - redis
